# Generated by Django 4.1.5 on 2023-02-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QR_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
